version: "3.12"

services:
  welbex:
    container_name: welbex
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  celery_beat:
    container_name: celery_beat
    build: .
    command: celery -A WelbeX beat -l INFO -S django
    environment:
      - C_FORCE_ROOT=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=WelbeX.settings
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - DEBUG=False
    depends_on:
      - redis
      - db
      - celery_worker
      - welbex
    volumes:
      - .:/app

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A WelbeX worker --loglevel=INFO -P eventlet
    environment:
      - C_FORCE_ROOT=true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=WelbeX.settings
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - DEBUG=False
    depends_on:
      - redis
      - db
      - welbex
    volumes:
      - .:/app

volumes:
  pgdata: {}
